backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "books"
    label: "Books"
    folder: "_books"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "events"
    label: "Events"
    folder: "_events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Event Name", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }


include:
  - admin

